### ISSUE TITLE
Bug sur l'authentification

### ISSUE THREAD

**Issue by lazarefortune** [lazarefortune/AS-Projet-synthese-2020-2021#1]
@Night4dead  j'ai cette erreur quand j'essaie de me connecter avec ton code:
"Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in C:\wamp64\www\projet-synthese\classes\User.php on line 9"
je pense ça provient du "protected string|null $id;"

**Comment by kuen-dev** [comment]
t'as passé ton php en php 8.0 ?
C'est ce que Intellij IDEA me proposait de faire pour que ça passe

**Comment by lazarefortune** [comment]
non j'ai la 7, mais faudrait pas bosser sur la dernière version je pense, ni sur une trop vieille version. Après on sait pas celle qui est sur les serveurs de l'iut, t'en pense quoi?

**Comment by kuen-dev** [comment]
Je sais pas, après le `protected string|null $id` c'est pour gérer la création d'un nouveau User qui n'a pas encore été ajouté à la base de données donc n'a pas encore eu son id auto-incrémenter. Je pense que ca reste utile, après à voir si on garde ça ou si on fait autrement.
Pour l'instant pour juste la gestion des vues et le test de connexion je pense qu'on peut laisser comme ca et en reparler à la réunion ?

**Comment by lazarefortune** [comment]
sauf que là ca va fonctionner uniquement sur ton pc à toi, pas en ligne ni sur nos pcs, et aussi tu peux uste mettre `protected string` et laisser comme ça, pas besoin de mettre ça dans la définition de l'attribut, vu que tu as déjà mis dans ton constructeur `int $id = null`

**Comment by kuen-dev** [comment]
j'vais corriger alors

**Comment by lazarefortune** [comment]
ok ça marche
